### ISSUE TITLE
The hash value of the integrity attribute of the script tag in INSTALL area is incorrect

### ISSUE THREAD

**Issue by ivan111** [jsdelivr/jsdelivr#18524] opened 2023-09-02 10:14 UTC
### Description

In INSTALL area, I changed to old version and "Copy HTML + SRI"
but copied script's hash value was incorrect.

for example,
the script of bootstrap's static version is
`<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha256-gOQJIa9+K/XdfAuBkg2ONAdw5EnQbokw/s2b8BqsRFg=" crossorigin="anonymous"></script>`
the script of version 5.3.0 is
`<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha256-gOQJIa9+K/XdfAuBkg2ONAdw5EnQbokw/s2b8BqsRFg=" crossorigin="anonymous"></script>`
The integrity attribute didn't change.

but in "Files" tab under the INSTALL area,
"Copy HTML + SRI"
is correct.

### Affected jsDelivr links

maybe all

### Response headers

```

```

### Information

- Device OS: Windows
- Browser & Version: Chrome 116
- Your location (country/region): Japan

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by jimaek** [comment] 2023-09-02 15:54
Why do you think the hash is incorrect? This tool seems to confirm that our hashes are correct https://www.srihash.org/

**Comment by MartinKolarik** [comment] 2023-09-02 16:42
Closing as a duplicate of https://github.com/jsdelivr/www.jsdelivr.com/issues/523

The website is open source so if you'd like to fix it, we'll welcome a PR.

**Closed** 2023-09-02 16:42 UTC
