### ISSUE TITLE
CDN ERROR

### ISSUE THREAD

**Issue by kqme** [jsdelivr/jsdelivr#18349] opened 2021-12-20 03:57 UTC
HTTPS certificate expired

**Comment by ljcbaby** [comment] 2021-12-20 04:14
同 #18348，不要另开了

**Comment by wordlesswind** [comment] 2021-12-20 06:16
与 #18348 重复，请关闭此 issue。
Duplicate of #18348, please close this issue.

**Closed** 2021-12-20 08:29 UTC
