### ISSUE TITLE
CDN problem

### ISSUE THREAD

**Issue by jdzy** [jsdelivr/jsdelivr#18355] opened 2021-12-20 06:05 UTC
Please repair it quickly , thanks

**Comment by ljcbaby** [comment] 2021-12-20 06:11
同 #18348，不要另开了

**Comment by wordlesswind** [comment] 2021-12-20 06:18
与 #18348 重复，请关闭此 issue。
Duplicate of #18348, please close this issue.

**Closed** 2021-12-20 08:30 UTC
