### ISSUE TITLE
 Lytebox JS library content viewer #2950 unicode unescaped chars

### ISSUE THREAD

**Issue by Fede72** [jsdelivr/jsdelivr#2951] opened 2015-01-06 11:56 UTC
The automatic check reports some  unicode unescaped chars, but the library is correct, there are some regex working with unicode chars.

Thanks

**Comment by megawac** [comment] 2015-01-06 14:39
Duplicate of https://github.com/jsdelivr/bot/issues/20

**Closed by megawac** 2015-01-06 14:39 UTC
