### ISSUE TITLE
SSL Issue on your every link

### ISSUE THREAD

**Issue by junaid63** [jsdelivr/jsdelivr#18567] opened 2024-05-02 06:59 UTC
### Description

https://cdn.jsdelivr.net/npm/sweetalert2@7.28.11/dist/

When I ma trying to access any of your link there is a privacy error please resolve as soon as possible

### Affected jsDelivr links

https://cdn.jsdelivr.net/npm/sweetalert2@7.28.11/dist/

### Response headers

```

```

### Information

- Device OS: [e.g. iOS, Windows, MacOS]
- Browser & Version: [e.g. Chrome 103, Safari 8, Firefox 108]
- VPN provider (if you use one)
- Your location (country/region)

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by rizkytegar** [comment] 2024-05-02 07:03
hello @junaid63,

Please try the following URL if you want to quickly access the CDN. But if you don't want to change the URL, please wait until this SSL issue is resolved:

```
https://fastly.jsdelivr.net/npm/sweetalert2@7.28.11/dist/
https://fastly.jsdelivr.net/npm/sweetalert2@7.28.11/dist/
```

Please read the following issue: [cdn.jsdelivr.net has SSL issue. #18565](https://github.com/jsdelivr/jsdelivr/issues/18565)

**Comment by junaid63** [comment] 2024-05-02 07:06
Thanks,
But please resolve the SSL issue as soon as possible.
________________________________

**Comment by khoau2u** [comment] 2024-05-02 07:25
I confirmed that cdn.jsdelivr.net on most regions now reporting ERR_CERT_COMMON_NAME_INVALID

**Comment by rcasunshare** [comment] 2024-05-02 07:26
Excuse me but don't you read first?

https://github.com/jsdelivr/jsdelivr/issues/18565

**Comment by khoau2u** [comment] 2024-05-02 07:29
> Excuse me but don't you read first?
> 
> #18565

OK, so this is a duplicate of #18565 
@junaid63 should mark this as closed.

**Comment by junaid63** [comment] 2024-05-02 07:32
Duplicate issue https://github.com/jsdelivr/jsdelivr/issues/18565

**Closed** 2024-05-02 07:32 UTC
