### ISSUE TITLE
Will QUANTIL become the sponsor of jsdelivr again?

### ISSUE THREAD

**Issue by cnzc** [jsdelivr/jsdelivr#18459] opened 2022-12-24 12:56 UTC
Will QUANTIL become the sponsor of jsdelivr again? 
QUANTIL is the largest CDN service provider in China. I think only QUANTIL can help jsdelivr return to Chinese Mainland. At present, fastly.jsdelivr.net seems to be inaccessible in some parts of China. Many Chinese websites are replacing jsdelivr with other CDNs, but other CDNs are not as good as jsdelivr. We are looking forward to jsdelivr restarting the Chinese CDN. Could you please contact QUANTIL to see if you can restart the Chinese CDN?

**Comment by jimaek** [comment] 2022-12-24 13:48
The problem is not Quantil but the cancellation of our ICP license which according to partners in China is now impossible to renew without transferring ownership of our main domain to an entity in China. And we cant do that.

So unfortunately I don't see any realistic solutions for now :(

Consider also testing gcore.jsdelivr.net, maybe it works better in China

**Closed by jimaek** 2022-12-24 13:48 UTC

**Comment by cnzc** [comment] 2022-12-25 02:53
OK, thank you. I will resubmit issues when there is a feasible way to restore the icp filing.
