### ISSUE TITLE
How to access the `@angular/core` npm package?

### ISSUE THREAD

**Issue by Roman-Lo** [jsdelivr/jsdelivr#18047] opened 2017-10-18 06:34 UTC
When searching the npm package of Angular4, which named `@angular/core`, it failed to display the package index page by the url `https://www.jsdelivr.com/package/npm/@angular/core`. Is it a route bug causing by the '@' sign in the package name?

**Comment by MartinKolarik** [comment] 2017-10-18 09:09
Hi @Roman-Lo, thanks for reporting the issue!

It is not caused by the `@` character but we'll investigate why it happens. In the meantime, you can check the directory listing page from the CDN: http://cdn.jsdelivr.net/npm/@angular/core/

**Comment by MartinKolarik** [comment] 2017-10-18 09:10
@haroenv any idea why the package is [11th in the search results](https://www.jsdelivr.com/?query=%40angular%2Fcore&page=1) for exact name match?

We need a way to retrieve information from your index based on package name, and I assumed the exact match will always be on the first result page. Is there a way to make sure that's the case (we'd prefer the exact match be always first anyway), or a better way to get data for just one package by name?

Also, possibly related, yarnpkg says this package had 0 downloads in the last 30 days, but npm says 2M.

**Comment by Haroenv** [comment] 2017-10-18 15:40
Npm doesn't give the downloads for scoped packages properly, so it has a lower relevance than it should have. This is tracked in https://github.com/algolia/npm-search/issues/61

**Comment by MartinKolarik** [comment] 2017-10-18 17:52
@Haroenv is there a way for us to retrieve information for a specific package by exact name?

**Comment by Haroenv** [comment] 2017-10-18 18:32
index.getObject('package-name') @MartinKolarik

**Comment by MartinKolarik** [comment] 2017-10-18 19:17
@Haroenv great, thanks!

**Comment by MartinKolarik** [comment] 2017-10-19 16:26
@Roman-Lo thanks again for reporting, the issue should be fixed now: https://www.jsdelivr.com/package/npm/@angular/core

**Closed by MartinKolarik** 2017-10-19 16:26 UTC

**Comment by Roman-Lo** [comment] 2017-10-29 02:55
Thank you all! It works now!
