### ISSUE TITLE
jsDelivr CDN is DOWN!!

### ISSUE THREAD

**Issue by chennien** [jsdelivr/jsdelivr#18353] opened 2021-12-20 05:40 UTC
cdn.jsdelivr.net is not listed on the common names of the installed SSL certificate.

**Comment by ljcbaby** [comment] 2021-12-20 05:52
同 #18348，不要另开了

**Comment by wordlesswind** [comment] 2021-12-20 06:17
与 #18348 重复，请关闭此 issue。
Duplicate of #18348, please close this issue.

**Closed** 2021-12-20 08:29 UTC
