### ISSUE TITLE
CDN service of China is broken!

### ISSUE THREAD

**Issue by yzyyz1387** [jsdelivr/jsdelivr#18352] opened 2021-12-20 05:30 UTC
**Describe the bug**
CDN service of China is broken!

**Affected jsDelivr links**
eg: https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js

**Comment by mouday** [comment] 2021-12-20 05:36
me too

**Comment by MrOrz** [comment] 2021-12-20 05:38
Please use #18348 instead.

**Comment by wordlesswind** [comment] 2021-12-20 06:17
与 #18348 重复，请关闭此 issue。
Duplicate of #18348, please close this issue.

**Closed** 2021-12-20 06:23 UTC
