### ISSUE TITLE
So here comes the problem about SSL

### ISSUE THREAD

**Issue by SukkaW** [jsdelivr/jsdelivr#18148] opened 2019-04-20 08:37 UTC
jsDelivr uses 2 Authoritative DNS Providers (currently they are NS1 and ClouDNS), uses AWS S3 as persistent storage, uses multiple instances hosted by DigitalOcean and other Cloud provider as cache server, even add Fastly not only as a CDN but also a load-balancer and extra cache layer. All these contribute to make jsDelivr as fastest and the most reliable open source CDN provider.

But since the expired SSL has ruined the jsDelivr experience in China, I think jsDelivr should add monitor for checking SSL status, not only focused on multi-cdn.
jsDelivr currently having auto-renewed shared SSL provided by Cloudflare and Fastly. I just have reached the [QUANTIL Portal Documents](https://portal.quantil.com/onlinehelp/PortalHelp.htm?AddSSLCertificate.htm) and find the QUANTIL also provides 'QUANTIL's Shared Certificate'. It should able to be auto-renewed just as Cloudflare's Universal SSL and Fastly's shared SSL. I think it can help to avoid expired SSL causing downtime.

**Comment by jimaek** [comment] 2019-04-20 08:54
Our deal with Quantil does not cover shared SSL unfortunately. But we soon plan to make some changes to our system that will prevent this from happening even if the SSL expires again.

**Comment by jimaek** [comment] 2019-04-20 11:29
I will close this as the issue is solved. More updates will be available on our twitter and blog

**Closed by jimaek** 2019-04-20 11:29 UTC
