### ISSUE TITLE
Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by tzh2017** [jsdelivr/jsdelivr#18351] opened 2021-12-20 04:06 UTC
as title

**Comment by ljcbaby** [comment] 2021-12-20 04:15
同 #18348，不要另开了

**Comment by wordlesswind** [comment] 2021-12-20 06:17
与 #18348 重复，请关闭此 issue。
Duplicate of #18348, please close this issue.

**Closed** 2021-12-20 08:30 UTC
